version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: entries
    ports:
      - "5433:5432"   # host port 5433 → container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5000:5000"


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  worker:
    build: ./worker
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started



volumes:
  postgres_data: